// <auto-generated />
namespace RiplTrackingSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addfrom_to : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addfrom_to));
        
        string IMigrationMetadata.Id
        {
            get { return "202108161947064_add-from_to"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
